
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: cityweatherapp_sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123456O. 
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: cityweatherapp_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  cityweatherapp:
    build: ./CityWeatherApp
    container_name: cityweatherapp_service
    depends_on:
      - sqlserver
      - redis
    ports:
      - "5000:80"  
    networks:
      - app-network
    restart: always  

networks:
  app-network:
    driver: bridge

volumes:
  sql_data:
  redis_data:
